describe('Header focus test', () => {
  it('should display focus states for each top level link on desktop', () => {
    cy.viewport("macbook-13");
    cy.visit('http://localhost:3000/components/header/with-mixed-levels-of-navigation/preview');
    cy.window().focus();
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
  })

  it('should display focus states for each top level link on mobile', () => {
    cy.viewport("iphone-6+");
    cy.visit('http://localhost:3000/components/header/with-mixed-levels-of-navigation/preview');
    cy.window().focus();
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
  })

  it('should display focus states for second level links and components on desktop', () => {
    cy.viewport("macbook-13");
    cy.visit('http://localhost:3000/components/header/with-mixed-levels-of-navigation/preview');
    cy.window().focus();
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.focused().realPress('Enter');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab')
    cy.wait(500)
    cy.realPress('Enter');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab')
    cy.wait(500)
  })

  it('should display focus states for second level links and components on mobile', () => {
    cy.viewport("iphone-6+");
    cy.visit('http://localhost:3000/components/header/with-mixed-levels-of-navigation/preview');
    cy.window().focus();
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.focused().realPress('Enter');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
    cy.focused().realPress('Enter');
    cy.wait(500)
    cy.realPress('Tab')
    cy.wait(500)
    cy.realPress('Tab');
    cy.wait(500)
  })
})

describe('Footer focus test', () => {
  it('should show focus states on all footer link elements in desktop', () => {
    cy.viewport("macbook-13");
    cy.visit('http://localhost:3000/components/footer/with-primary,-secondary-and-utility-navigation,-sponsor-image-and-social-navigation/preview')
    cy.window().focus();
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
  })

  it('should show focus states on all footer link elements in mobile', () => {
    cy.viewport("iphone-6+");
    cy.visit('http://localhost:3000/components/footer/with-primary,-secondary-and-utility-navigation,-sponsor-image-and-social-navigation/preview')
    cy.window().focus();
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
    cy.realPress('Tab');
    cy.wait(500);
  })
})